import { Tool, ToolCategory } from './types';
import { 
  MergeIcon, SplitIcon, CompressIcon, EditIcon, SignIcon, WordToPdfIcon, 
  PdfToWordIcon, PdfToPowerpointIcon, PdfToExcelIcon, PowerpointToPdfIcon, 
  ExcelToPdfIcon, PdfToJpgIcon, JpgToPdfIcon, WatermarkIcon, RotateIcon, 
  HtmlToPdfIcon, UnlockIcon, ProtectIcon, OrganizeIcon, PdfToPdfaIcon, 
  RepairIcon, PageNumbersIcon, ScanToPdfIcon, OcrPdfIcon,
  CompressImageIcon, ResizeImageIcon, CropImageIcon, ImageToJpgIcon, 
  JpgToImageIcon, RotateImageIcon, FlipImageIcon, WatermarkImageIcon,
  RemoveBgIcon, UpscaleImageIcon
} from './components/icons';

export const CATEGORIES: ToolCategory[] = [
  'Organize PDF', 'Optimize PDF', 'Convert PDF', 'Edit PDF', 'PDF Security', 'Workflows',
  'Image Tools', 'Optimize Image', 'Edit Image', 'Convert Image',
  'Video Tools', 'Convert Video', 'Edit Video'
];

export const TOOLS: Tool[] = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    Icon: MergeIcon,
    color: 'bg-red-500',
    hoverColor: 'hover:bg-red-600',
    minFiles: 2,
    category: 'Organize PDF',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    Icon: SplitIcon,
    color: 'bg-orange-500',
    hoverColor: 'hover:bg-orange-600',
    minFiles: 1,
    category: 'Organize PDF',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    Icon: CompressIcon,
    color: 'bg-yellow-500',
    hoverColor: 'hover:bg-yellow-600',
    minFiles: 1,
    category: 'Optimize PDF',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Easily convert your PDF files into easy to edit DOC and DOCX documents.',
    Icon: PdfToWordIcon,
    color: 'bg-blue-500',
    hoverColor: 'hover:bg-blue-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
    Icon: PdfToPowerpointIcon,
    color: 'bg-red-700',
    hoverColor: 'hover:bg-red-800',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Pull data straight from PDFs and convert them into XLS spreadsheets.',
    Icon: PdfToExcelIcon,
    color: 'bg-green-600',
    hoverColor: 'hover:bg-green-700',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    Icon: WordToPdfIcon,
    color: 'bg-blue-700',
    hoverColor: 'hover:bg-blue-800',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    Icon: PowerpointToPdfIcon,
    color: 'bg-orange-600',
    hoverColor: 'hover:bg-orange-700',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Make XLS and XLSX spreadsheets easy to read by converting them to PDF.',
    Icon: ExcelToPdfIcon,
    color: 'bg-green-700',
    hoverColor: 'hover:bg-green-800',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF document.',
    Icon: EditIcon,
    color: 'bg-indigo-500',
    hoverColor: 'hover:bg-indigo-600',
    minFiles: 1,
    category: 'Edit PDF',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
    Icon: PdfToJpgIcon,
    color: 'bg-teal-500',
    hoverColor: 'hover:bg-teal-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF. Adjust orientation and margins.',
    Icon: JpgToPdfIcon,
    color: 'bg-pink-500',
    hoverColor: 'hover:bg-pink-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Sign yourself or send signature requests to others. No need for printing.',
    Icon: SignIcon,
    color: 'bg-purple-500',
    hoverColor: 'hover:bg-purple-600',
    minFiles: 1,
    category: 'Workflows',
  },
  {
    id: 'watermark',
    name: 'Watermark',
    description: 'Stamp an image or text over your PDFs in seconds. Choose the typography and transparency.',
    Icon: WatermarkIcon,
    color: 'bg-cyan-500',
    hoverColor: 'hover:bg-cyan-600',
    minFiles: 1,
    category: 'Edit PDF',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once.',
    Icon: RotateIcon,
    color: 'bg-gray-500',
    hoverColor: 'hover:bg-gray-600',
    minFiles: 1,
    category: 'Organize PDF',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF. Copy and paste the URL of the page you want.',
    Icon: HtmlToPdfIcon,
    color: 'bg-lime-500',
    hoverColor: 'hover:bg-lime-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
    Icon: UnlockIcon,
    color: 'bg-amber-600',
    hoverColor: 'hover:bg-amber-700',
    minFiles: 1,
    category: 'PDF Security',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.',
    Icon: ProtectIcon,
    color: 'bg-rose-500',
    hoverColor: 'hover:bg-rose-600',
    minFiles: 1,
    category: 'PDF Security',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort pages of your PDF file as you wish. Delete PDF pages or add PDF pages.',
    Icon: OrganizeIcon,
    color: 'bg-sky-500',
    hoverColor: 'hover:bg-sky-600',
    minFiles: 1,
    category: 'Organize PDF',
  },
  {
    id: 'extract-pages',
    name: 'Extract PDF Pages',
    description: 'Extract specific pages from your PDF to create a new document.',
    Icon: SplitIcon,
    color: 'bg-teal-600',
    hoverColor: 'hover:bg-teal-700',
    minFiles: 1,
    category: 'Organize PDF',
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving.',
    Icon: PdfToPdfaIcon,
    color: 'bg-fuchsia-500',
    hoverColor: 'hover:bg-fuchsia-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Repair a damaged PDF and recover data from a corrupt PDF with our Repair tool.',
    Icon: RepairIcon,
    color: 'bg-stone-500',
    hoverColor: 'hover:bg-stone-600',
    minFiles: 1,
    category: 'Optimize PDF',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers into your PDFs with ease. Choose your positions, dimensions, typography.',
    Icon: PageNumbersIcon,
    color: 'bg-violet-500',
    hoverColor: 'hover:bg-violet-600',
    minFiles: 1,
    category: 'Organize PDF',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Scan documents from your mobile device and send them instantly to your browser.',
    Icon: ScanToPdfIcon,
    color: 'bg-emerald-500',
    hoverColor: 'hover:bg-emerald-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Recognize text in your scanned PDFs to create searchable and selectable files.',
    Icon: OcrPdfIcon,
    color: 'bg-blue-gray-500',
    hoverColor: 'hover:bg-blue-gray-600',
    minFiles: 1,
    category: 'Convert PDF',
  },
  // Image Tools
  {
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Compress JPG, PNG, SVG or GIF with the best quality and compression.',
    Icon: CompressImageIcon,
    color: 'bg-purple-500',
    hoverColor: 'hover:bg-purple-600',
    minFiles: 1,
    category: 'Optimize Image',
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    description: 'Define your own pixels to resize your image. It is that simple.',
    Icon: ResizeImageIcon,
    color: 'bg-blue-500',
    hoverColor: 'hover:bg-blue-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    description: 'Crop JPG, PNG or GIF by defining your own pixels to crop it.',
    Icon: CropImageIcon,
    color: 'bg-green-500',
    hoverColor: 'hover:bg-green-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'image-to-jpg',
    name: 'Convert to JPG',
    description: 'Convert PNG, GIF, WEBP, or other formats to JPG.',
    Icon: ImageToJpgIcon,
    color: 'bg-yellow-500',
    hoverColor: 'hover:bg-yellow-600',
    minFiles: 1,
    category: 'Convert Image',
  },
  {
    id: 'jpg-to-png',
    name: 'Convert from JPG',
    description: 'Convert JPG to PNG or WEBP format.',
    Icon: JpgToImageIcon,
    color: 'bg-pink-500',
    hoverColor: 'hover:bg-pink-600',
    minFiles: 1,
    category: 'Convert Image',
  },
  {
    id: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate images JPG, PNG or GIF at the same time.',
    Icon: RotateImageIcon,
    color: 'bg-indigo-500',
    hoverColor: 'hover:bg-indigo-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'flip-image',
    name: 'Flip Image',
    description: 'Flip images horizontally or vertically with a single click.',
    Icon: FlipImageIcon,
    color: 'bg-teal-500',
    hoverColor: 'hover:bg-teal-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'watermark-image',
    name: 'Watermark Image',
    description: 'Stamp an image or text over your images in seconds.',
    Icon: WatermarkImageIcon,
    color: 'bg-orange-500',
    hoverColor: 'hover:bg-orange-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    description: 'Easily remove background from images automatically.',
    Icon: RemoveBgIcon,
    color: 'bg-red-500',
    hoverColor: 'hover:bg-red-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'upscale-image',
    name: 'Upscale Image',
    description: 'Enlarge images without losing quality using AI.',
    Icon: UpscaleImageIcon,
    color: 'bg-cyan-500',
    hoverColor: 'hover:bg-cyan-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    description: 'Add top and bottom text to images in classic meme style.',
    Icon: EditIcon,
    color: 'bg-fuchsia-500',
    hoverColor: 'hover:bg-fuchsia-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'grayscale-image',
    name: 'Grayscale',
    description: 'Convert images to black and white.',
    Icon: EditIcon,
    color: 'bg-gray-600',
    hoverColor: 'hover:bg-gray-700',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'blur-image',
    name: 'Blur Image',
    description: 'Apply Gaussian blur effect to soften images.',
    Icon: EditIcon,
    color: 'bg-blue-400',
    hoverColor: 'hover:bg-blue-500',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'sharpen-image',
    name: 'Sharpen Image',
    description: 'Enhance image sharpness and detail.',
    Icon: EditIcon,
    color: 'bg-emerald-500',
    hoverColor: 'hover:bg-emerald-600',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'brightness-image',
    name: 'Adjust Brightness',
    description: 'Make images brighter or darker.',
    Icon: EditIcon,
    color: 'bg-yellow-400',
    hoverColor: 'hover:bg-yellow-500',
    minFiles: 1,
    category: 'Edit Image',
  },
  {
    id: 'contrast-image',
    name: 'Adjust Contrast',
    description: 'Increase or decrease image contrast.',
    Icon: EditIcon,
    color: 'bg-purple-400',
    hoverColor: 'hover:bg-purple-500',
    minFiles: 1,
    category: 'Edit Image',
  },
  // Video Tools
  {
    id: 'compress-video',
    name: 'Compress Video',
    description: 'Reduce video file size while maintaining quality.',
    Icon: CompressIcon,
    color: 'bg-purple-600',
    hoverColor: 'hover:bg-purple-700',
    minFiles: 1,
    category: 'Convert Video',
  },
  {
    id: 'video-to-mp4',
    name: 'Convert to MP4',
    description: 'Convert any video format to MP4.',
    Icon: CompressIcon,
    color: 'bg-blue-600',
    hoverColor: 'hover:bg-blue-700',
    minFiles: 1,
    category: 'Convert Video',
  },
  {
    id: 'convert-video',
    name: 'Convert Video Format',
    description: 'Convert videos between MP4, AVI, MOV, MKV, WEBM, and FLV formats.',
    Icon: CompressIcon,
    color: 'bg-indigo-600',
    hoverColor: 'hover:bg-indigo-700',
    minFiles: 1,
    category: 'Convert Video',
  },
  {
    id: 'trim-video',
    name: 'Trim Video',
    description: 'Cut and trim videos to desired length.',
    Icon: SplitIcon,
    color: 'bg-green-600',
    hoverColor: 'hover:bg-green-700',
    minFiles: 1,
    category: 'Edit Video',
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Convert video clips to animated GIFs.',
    Icon: CompressIcon,
    color: 'bg-pink-600',
    hoverColor: 'hover:bg-pink-700',
    minFiles: 1,
    category: 'Convert Video',
  },
  {
    id: 'extract-audio',
    name: 'Extract Audio',
    description: 'Extract audio track from video files.',
    Icon: SplitIcon,
    color: 'bg-orange-600',
    hoverColor: 'hover:bg-orange-700',
    minFiles: 1,
    category: 'Edit Video',
  },
];
