
const FILE_IS_TOO_BIG = 'FILE_IS_TOO_BIG';
const NOT_ENOUGH_STORAGE = 'NOT_ENOUGH_STORAGE';
const EMPTY_TRASH = 'EMPTY_TRASH';

export default {
  FILE_IS_TOO_BIG,
  NOT_ENOUGH_STORAGE,
  EMPTY_TRASH,
};
